// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentAttendanceMVC.Data;

#nullable disable

namespace StudentAttendanceMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250925163004_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentAttendanceMVC.Models.ClassSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ClassSessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseName = "Lập trình Web",
                            Date = new DateTime(2025, 9, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Room = "Phòng 101",
                            Time = "08:00 - 10:00"
                        },
                        new
                        {
                            Id = 2,
                            CourseName = "Cơ sở dữ liệu",
                            Date = new DateTime(2025, 9, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            Room = "Phòng 102",
                            Time = "13:00 - 15:00"
                        });
                });

            modelBuilder.Entity("StudentAttendanceMVC.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("LecturerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseName = "Lập trình Web",
                            Date = new DateTime(2025, 9, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            LecturerName = "Giảng viên A",
                            Room = "Phòng 101",
                            StudentName = "",
                            Time = "08:00 - 10:00"
                        },
                        new
                        {
                            Id = 2,
                            CourseName = "Cơ sở dữ liệu",
                            Date = new DateTime(2025, 9, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            LecturerName = "Giảng viên A",
                            Room = "Phòng 102",
                            StudentName = "",
                            Time = "13:00 - 15:00"
                        });
                });

            modelBuilder.Entity("StudentAttendanceMVC.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attended")
                        .HasColumnType("bit");

                    b.Property<int>("ClassSessionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClassSessionId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Attended = false,
                            ClassSessionId = 1,
                            Name = "Sinh viên X"
                        },
                        new
                        {
                            Id = 2,
                            Attended = false,
                            ClassSessionId = 1,
                            Name = "Sinh viên Y"
                        },
                        new
                        {
                            Id = 3,
                            Attended = false,
                            ClassSessionId = 1,
                            Name = "Sinh viên Z"
                        },
                        new
                        {
                            Id = 4,
                            Attended = false,
                            ClassSessionId = 2,
                            Name = "Sinh viên X"
                        },
                        new
                        {
                            Id = 5,
                            Attended = false,
                            ClassSessionId = 2,
                            Name = "Sinh viên Y"
                        });
                });

            modelBuilder.Entity("StudentAttendanceMVC.Models.Student", b =>
                {
                    b.HasOne("StudentAttendanceMVC.Models.ClassSession", "ClassSession")
                        .WithMany("Students")
                        .HasForeignKey("ClassSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassSession");
                });

            modelBuilder.Entity("StudentAttendanceMVC.Models.ClassSession", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
