// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentAttendanceMVC.Data;

#nullable disable

namespace StudentAttendanceMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251002093440_AddIsAttendanceTakenToClassSession")]
    partial class AddIsAttendanceTakenToClassSession
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("StudentAttendanceMVC.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("StudentAttendanceMVC.Models.ClassSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAttendanceTaken")
                        .HasColumnType("bit");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.ToTable("ClassSessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseName = "Lập trình Web",
                            Date = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAttendanceTaken = false,
                            Room = "Phòng 101",
                            ScheduleId = 1,
                            Time = "08:00 - 10:00"
                        },
                        new
                        {
                            Id = 2,
                            CourseName = "Cơ sở dữ liệu",
                            Date = new DateTime(2025, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAttendanceTaken = false,
                            Room = "Phòng 102",
                            ScheduleId = 2,
                            Time = "13:00 - 15:00"
                        },
                        new
                        {
                            Id = 3,
                            CourseName = "Toán cao cấp",
                            Date = new DateTime(2025, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAttendanceTaken = false,
                            Room = "Phòng 103",
                            ScheduleId = 3,
                            Time = "09:00 - 11:00"
                        });
                });

            modelBuilder.Entity("StudentAttendanceMVC.Models.Schedules", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LecturerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseName = "Lập trình Web",
                            Date = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LecturerName = "lecturer@example.com",
                            Room = "Phòng 101",
                            StudentName = "student@example.com",
                            Time = "08:00 - 10:00"
                        },
                        new
                        {
                            Id = 2,
                            CourseName = "Cơ sở dữ liệu",
                            Date = new DateTime(2025, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LecturerName = "lecturer@example.com",
                            Room = "Phòng 102",
                            StudentName = "student@example.com",
                            Time = "13:00 - 15:00"
                        },
                        new
                        {
                            Id = 3,
                            CourseName = "Toán cao cấp",
                            Date = new DateTime(2025, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LecturerName = "lecturer@example.com",
                            Room = "Phòng 103",
                            StudentName = "student2@example.com",
                            Time = "09:00 - 11:00"
                        });
                });

            modelBuilder.Entity("StudentAttendanceMVC.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attended")
                        .HasColumnType("bit");

                    b.Property<int>("ClassSessionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClassSessionId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Attended = true,
                            ClassSessionId = 1,
                            Name = "Nguyễn Văn A"
                        },
                        new
                        {
                            Id = 2,
                            Attended = false,
                            ClassSessionId = 1,
                            Name = "Trần Thị B"
                        },
                        new
                        {
                            Id = 3,
                            Attended = true,
                            ClassSessionId = 1,
                            Name = "Lê Văn C"
                        },
                        new
                        {
                            Id = 4,
                            Attended = false,
                            ClassSessionId = 1,
                            Name = "Phạm Thị D"
                        },
                        new
                        {
                            Id = 5,
                            Attended = true,
                            ClassSessionId = 1,
                            Name = "Hoàng Văn E"
                        },
                        new
                        {
                            Id = 6,
                            Attended = false,
                            ClassSessionId = 1,
                            Name = "Đỗ Thị F"
                        },
                        new
                        {
                            Id = 7,
                            Attended = true,
                            ClassSessionId = 1,
                            Name = "Bùi Văn G"
                        },
                        new
                        {
                            Id = 8,
                            Attended = false,
                            ClassSessionId = 1,
                            Name = "Ngô Thị H"
                        },
                        new
                        {
                            Id = 9,
                            Attended = true,
                            ClassSessionId = 1,
                            Name = "Vũ Văn I"
                        },
                        new
                        {
                            Id = 10,
                            Attended = false,
                            ClassSessionId = 1,
                            Name = "Dương Thị K"
                        },
                        new
                        {
                            Id = 11,
                            Attended = true,
                            ClassSessionId = 1,
                            Name = "Lý Văn L"
                        },
                        new
                        {
                            Id = 12,
                            Attended = false,
                            ClassSessionId = 1,
                            Name = "Trịnh Thị M"
                        },
                        new
                        {
                            Id = 13,
                            Attended = false,
                            ClassSessionId = 2,
                            Name = "Nguyễn Văn A"
                        },
                        new
                        {
                            Id = 14,
                            Attended = true,
                            ClassSessionId = 2,
                            Name = "Trần Thị B"
                        },
                        new
                        {
                            Id = 15,
                            Attended = false,
                            ClassSessionId = 2,
                            Name = "Lê Văn C"
                        },
                        new
                        {
                            Id = 16,
                            Attended = true,
                            ClassSessionId = 2,
                            Name = "Phạm Thị D"
                        },
                        new
                        {
                            Id = 17,
                            Attended = false,
                            ClassSessionId = 2,
                            Name = "Hoàng Văn E"
                        },
                        new
                        {
                            Id = 18,
                            Attended = true,
                            ClassSessionId = 2,
                            Name = "Đỗ Thị F"
                        },
                        new
                        {
                            Id = 19,
                            Attended = false,
                            ClassSessionId = 2,
                            Name = "Bùi Văn G"
                        },
                        new
                        {
                            Id = 20,
                            Attended = true,
                            ClassSessionId = 2,
                            Name = "Ngô Thị H"
                        },
                        new
                        {
                            Id = 21,
                            Attended = false,
                            ClassSessionId = 2,
                            Name = "Vũ Văn I"
                        },
                        new
                        {
                            Id = 22,
                            Attended = true,
                            ClassSessionId = 2,
                            Name = "Dương Thị K"
                        },
                        new
                        {
                            Id = 23,
                            Attended = false,
                            ClassSessionId = 2,
                            Name = "Lý Văn L"
                        },
                        new
                        {
                            Id = 24,
                            Attended = true,
                            ClassSessionId = 2,
                            Name = "Trịnh Thị M"
                        },
                        new
                        {
                            Id = 25,
                            Attended = false,
                            ClassSessionId = 2,
                            Name = "Hà Văn N"
                        },
                        new
                        {
                            Id = 26,
                            Attended = true,
                            ClassSessionId = 3,
                            Name = "Nguyễn Văn A"
                        },
                        new
                        {
                            Id = 27,
                            Attended = false,
                            ClassSessionId = 3,
                            Name = "Trần Thị B"
                        },
                        new
                        {
                            Id = 28,
                            Attended = true,
                            ClassSessionId = 3,
                            Name = "Lê Văn C"
                        },
                        new
                        {
                            Id = 29,
                            Attended = false,
                            ClassSessionId = 3,
                            Name = "Phạm Thị D"
                        },
                        new
                        {
                            Id = 30,
                            Attended = true,
                            ClassSessionId = 3,
                            Name = "Hoàng Văn E"
                        },
                        new
                        {
                            Id = 31,
                            Attended = false,
                            ClassSessionId = 3,
                            Name = "Đỗ Thị F"
                        },
                        new
                        {
                            Id = 32,
                            Attended = true,
                            ClassSessionId = 3,
                            Name = "Bùi Văn G"
                        },
                        new
                        {
                            Id = 33,
                            Attended = false,
                            ClassSessionId = 3,
                            Name = "Ngô Thị H"
                        },
                        new
                        {
                            Id = 34,
                            Attended = true,
                            ClassSessionId = 3,
                            Name = "Vũ Văn I"
                        },
                        new
                        {
                            Id = 35,
                            Attended = false,
                            ClassSessionId = 3,
                            Name = "Dương Thị K"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("StudentAttendanceMVC.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("StudentAttendanceMVC.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentAttendanceMVC.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("StudentAttendanceMVC.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentAttendanceMVC.Models.ClassSession", b =>
                {
                    b.HasOne("StudentAttendanceMVC.Models.Schedules", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("StudentAttendanceMVC.Models.Student", b =>
                {
                    b.HasOne("StudentAttendanceMVC.Models.ClassSession", "ClassSession")
                        .WithMany("Students")
                        .HasForeignKey("ClassSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassSession");
                });

            modelBuilder.Entity("StudentAttendanceMVC.Models.ClassSession", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
